# Translated from `cat /opt/otrs/var/cron/*.dist`
---
- cron: name="DeleteCache"
        user=otrs
        job="$HOME/bin/otrs.DeleteCache.pl --expired > /dev/null"
        minute=20
        hour=0
        weekday=0

- cron: name="LoaderCache"
        user=otrs
        job="$HOME/bin/otrs.LoaderCache.pl -o delete > /dev/null"
        minute=30
        hour=0
        weekday=0

# fetch every 5 minutes emails via fetchmail
#*/5 * * * * [ -x /usr/bin/fetchmail ] && /usr/bin/fetchmail -a > /dev/null
#*/5 * * * *    /usr/bin/fetchmail -a --ssl > /dev/null

- cron: name="GenerateDashboardStats"
        user=otrs
        job="$HOME/bin/otrs.GenerateDashboardStats.pl > /dev/null"
        minute=5

- cron: name="GenericAgent-db"
        user=otrs
        job="$HOME/bin/otrs.GenericAgent.pl -c db > /dev/null"
        minute=*/10

- cron: name="GenericAgent"
        user=otrs
        job="$HOME/bin/otrs.GenericAgent.pl > /dev/null"
        minute=*/20

# example to execute otrs.GenericAgent.pl on 23:00 with
# Kernel::Config::GenericAgentMove job file
#0 23 * * * $HOME/bin/otrs.GenericAgent.pl -c "Kernel::Config::GenericAgentMove" > /dev/null

- cron: name="PendingJobs"
        user=otrs
        job="$HOME/bin/otrs.PendingJobs.pl > /dev/null"
        minute=45
        hour=*/2

- cron: name="ReprocessMails"
        user=otrs
        job="$HOME/bin/otrs.ReprocessMails.pl > /dev/null"
        minute=10
        hour=0

- cron: name="PostMasterMailbox"
        user=otrs
        job="$HOME/bin/otrs.PostMasterMailbox.pl > /dev/null"
        minute=*/10

- cron: name="RebuildTicketIndex"
        user=otrs
        job="$HOME/bin/otrs.RebuildTicketIndex.pl > /dev/null"
        minute=1
        hour=1

- cron: name="Scheduler"
        user=otrs
        job="$HOME/bin/otrs.Scheduler.pl -w 1 > /dev/null"
        minute=*/5

- cron: name="DeleteSessionIDs"
        user=otrs
        job="$HOME/bin/otrs.DeleteSessionIDs.pl --expired > /dev/null"
        minute=55

- cron: name="UnlockTickets"
        user=otrs
        job="$HOME/bin/otrs.UnlockTickets.pl --timeout > /dev/null"
        minute=35
